# All secrets in this file are for testing purposes are not a part of actual deployment
#
# TODO: database volume should be mounted from the system itself and should not reside in docker volume
# TODO: change all of temporary valures to environmental variables
version: '3.8'
services:
  sozisel-database:
    image: postgres:12.2
    container_name: sozisel-database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PORT: 5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  sozisel-backend:
    image: bombardierzy/sozisel-backend:latest
    container_name: sozisel-backend
    environment:
      HOST: ${HOST}
      PORT: 4000
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_PORT: 5432
      MEDIA_UPLOAD: /media_resources/
    volumes:
      - ./media_resources:/media_resources
    ports:
      - 4000:4000
    depends_on:
      - sozisel-database

  sozisel-frontend:
    image: bombardierzy/sozisel-frontend:latest
    container_name: sozisel-frontend
    depends_on:
      - sozisel-backend
    ports:
      - 9906:80