version: '3.8'
services:
  sozisel-router:
    image: bombardierzy/sozisel-router:latest
    container_name: sozisel-router
    ports:
      - 9906:80

  sozisel-database:
    image: postgres:12.2
    container_name: sozisel-database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PORT: 5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  sozisel-backend:
    image: bombardierzy/sozisel-backend:latest
    container_name: sozisel-backend
    environment:
      HOST: ${HOST}
      PORT: 4000
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_PORT: 5432
    volumes:
      - ./media_resources:/data/resources
    depends_on:
      - sozisel-database

  sozisel-frontend:
    image: bombardierzy/sozisel-frontend:latest
    container_name: sozisel-frontend
    depends_on:
      - sozisel-backend